[package]
name = "hma"
version = "0.1.0"
authors = ["HoshinoTented <limbolrain@gmail.com>"]
license-file = "LICENSE.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
